### ISSUE TITLE
Chinese Translation for v1.9.0

### ISSUE THREAD

**Issue by MemeK1d** [DabbingEevee/Moar-TCon#1]
Hey there,is the ring still developing?It has been appeared in the \assets\tconstruct\book\en_us\tools.It would be great to wear both the gauntlet and the ring,I'm looking forword to it. :)
[zh_cn.zip](https://github.com/DabbingEevee/Moar-TCon/files/11848528/zh_cn.zip)

**Comment by DabbingEevee** [comment]
Although the ring itself is finished, I will most likely add additional features to it. They are part of the baubles cross compat. Also is it possible to commit the translations next time. It saves me a lot of time. Thanks for the translation though. I will probably add then later today.

**Comment by MemeK1d** [comment]
> Although the ring itself is finished, I will most likely add additional features to it. They are part of the baubles cross compat. Also is it possible to commit the translations next time. It saves me a lot of time. Thanks for the translation though. I will probably add then later today.

Sorry there's some mistakes in the file.I will give you a new one.
[zh_cn.zip](https://github.com/DabbingEevee/Moar-TCon/files/11928667/zh_cn.zip)

**Comment by DabbingEevee** [comment]
in the future please make a pull request. it is much easier to manage that way
