### ISSUE TITLE
Ebonite is missing a LANG key.

### ISSUE THREAD

**Issue by Handeril** [DabbingEevee/Moar-TCon#10]
Small bug, but Ebonite is missing fluid.moretcon.liquidebonite in it's LANG files.
![2023-10-13_17 05 03](https://github.com/DabbingEevee/Moar-TCon/assets/83894721/05d2568e-b984-45b3-82da-c17d2979e5fe)

**Comment by DabbingEevee** [comment]
will be fixed in the next release, however I doubt that would be anytime soon.
