### ISSUE TITLE
server startup crash

### ISSUE THREAD

**Issue by SinusoidalC** [DabbingEevee/Moar-TCon#11]
[crash-2023-12-08_00.17.42-server.txt](https://github.com/DabbingEevee/Moar-TCon/files/13623106/crash-2023-12-08_00.17.42-server.txt)

**Comment by SinusoidalC** [comment]
moartcon version 1.10.2

**Comment by SinusoidalC** [comment]
1.11.0b could run on server

**Comment by DabbingEevee** [comment]
you are using an old version. latest stable version is 1.10.2_1.
