### ISSUE TITLE
[Suggestion] Embossment II for Armor?

### ISSUE THREAD

**Issue by Handeril** [DabbingEevee/Moar-TCon#13]
I'm really happy to see Embossment II in general for tools, and as a bonus, it "plays nice" with another mod I'm using to make certain embossments stackable.

I'm curious if this will possibly be carried over to Construct's Armory sometime soon?

**Comment by DabbingEevee** [comment]
this would probably be when the constructs armory support update comes out, which I don't think would be for a while.

**Comment by Handeril** [comment]
Is there plans to add an Embossment III and/or above, by chance?

**Comment by DabbingEevee** [comment]
no
