### ISSUE TITLE
CT Unable to Modify Fluid Recipes

### ISSUE THREAD

**Issue by EdwinYoungSteve** [DabbingEevee/Moar-TCon#20]
Use examples such as 
`Alloy.removeRecipe(<fluid:liquidrotiron>); `
The CraftTweaker script for Molten Rotiron will not remove molten Rotiron's alloy recipe, which can cause serious interference with modpack production, causing some players to obtain the fluid in ways modpacker does not want.
Presumably you are adding an enhancement script to the MOD to prevent the recipe from failing, if you can fix this, great, thank you very much :)

**Comment by DabbingEevee** [comment]
Issue will be investigated.

However, I am not using a script to add in the recipes. I am simply calling a method to add the recipes in using Java
There is no priority afaik.

**Comment by DabbingEevee** [comment]
this has been fixed and will be present in the next update

**Comment by EdwinYoungSteve** [comment]
Thank u very much :)

**Comment by DabbingEevee** [comment]
np
